apiVersion: apps/v1
kind: Deployment
metadata:
  name: meetup-meetings
  labels:
    app: meetup-meetings
    project: meetup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meetup-meetings
  template:
    metadata:
      labels:
        app: meetup-meetings
    spec:
      containers:
      - name: meetup-meetings
        image: gbrotas/meetup-meetings:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources: {}
        env:
          - name: ENVIRONMENT
            value: prod
          - name: DB_HOST
            value: postgres
          - name: DB_USER
            value: admin
          - name: DB_PASS
            value: psltest
          - name: DB_NAME
            value: postgresdb
          - name: kafka_clientID
            value: meetings
          - name: kafka_brokers
            value: 'my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092'
          - name: category_url
            value: 'http://categories-svc:4001'