apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: auth
spec:
  selector:
    app: meetup-auth
  type: ClusterIP
  ports:
    - name: auth-svc
      port: 4002
      targetPort: 4002
      protocol: TCP

    - name: auth-https
      targetPort: 443
      port: 443
      protocol: TCP