apiVersion: apps/v1
kind: Deployment
metadata:
  name: meetup-auth
  namespace: auth
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: meetup-auth
        image: gbrotas/meetup-auth:1.0.1
        ports:
        - containerPort: 4002
        resources: {}
        env:
          - name: apiUrl
            value: http://auth.meetup.info
        envFrom:
          - secretRef:
              name: meetup-auth-secrets